src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import group.urls
import students.urls
import teachers.urls
from core.views import (IndexView, Custom404View, UserLoginView,
                        UserLogoutView, UserRegistrationView, send_test_email,
                        ActivateUserView, UserProfileView)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("__debug__/", include("debug_toolbar.urls")),
    path('jet/', include('jet.urls', 'jet')),
    path("admin/", admin.site.urls),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate_user"),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("students/", include(students.urls)),
    path("teachers/", include(teachers.urls)),
    path("groups/", include(group.urls)),
    path("oauth/", include("social_django.urls", namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()

handler404 = Custom404View.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/group/urls.py
from django.urls import path
from group.views import GroupListView, GroupCreate, GroupUpdateView, GroupDeleteView, GroupDetailView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("create/", GroupCreate.as_view(), name="group_create"),
    path("update/<int:pk>/", GroupUpdateView.as_view(), name="update_group"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("details/<int:pk>/", GroupDetailView.as_view(), name="details_group"),
]

src/students/urls.py
from django.urls import path
from .views import StudentListView, StudentCreate, StudentUpdateView, StudentDeleteView

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("create/", StudentCreate.as_view(), name="create_student"),
    path("update/<int:pk>/", StudentUpdateView.as_view(), name="update_student"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="delete_student"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreate, TeacherUpdateView, TeacherDeleteView

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="teachers_list"),
    path("create/", TeacherCreate.as_view(), name="teacher_create"),
    path("update/<int:pk>/", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", TeacherDeleteView.as_view(), name="delete_teacher"),
]

src/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Cover Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .nav-link:hover {
        color:#0d6efd;
      }
      textarea {
        height: 5em;
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-white bg-dark">
    
<div class="cover-container d-flex w-100 h-100 mx-auto flex-column">
  <header>
    <div class=" d-flex">
      <p style="width: 12%" class="m-0 p-2">
        <a class="navbar-brand fs-3" href="{% url 'index' %}">MY LMS</a>
      </p>
      <nav style="width: 80%"class="navbar navbar-expand-lg bg-dark border-bottom border-bottom-dark d-flex justify-content-center gap-5" data-bs-theme="dark">
        <a class="nav-link fs-5" href="{% url 'students:get_students' %}">Students</a>
        <a class="nav-link fs-5" href="{% url 'teachers:teachers_list' %}">Teachers</a>
        <a class="nav-link fs-5" href="{% url 'groups:group_list' %}">Groups</a>
        <div class="nav-link dropdown text-end">
          <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>
          <ul class="dropdown-menu text-small" style="">
            {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="">{{ user.first_name|title }} {{ user.last_name|title }}</a></li>
                <li><a class="dropdown-item" href="{% url 'user_profile' user.id %}">Profile</a></li>
                <li><a class="dropdown-item" href="#">Change password</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout...</a></li>
            {% else %}
                <li><a class="dropdown-item" href="{% url 'login' %}">Login...</a></li>
                <li><a class="dropdown-item" href="{% url 'register' %}">Registration</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Reset password</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'social:begin' 'google-oauth2' %}">Registration via Google</a></li>
                <li><a class="dropdown-item" href="{% url 'social:begin' 'facebook' %}">Registration via Facebook</a></li>
                <li><a class="dropdown-item" href="{% url 'social:begin' 'github' %}">Registration via GitHub</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
  </header>

  <main class="px-3 cover-container">
      {% block content %}
        <h1 class="p-5"> Learning Management System</h1>
          <img style="width: 20%" src="https://cdn-icons-png.flaticon.com/512/1903/1903172.png">
        <p class="lead p-3">Access information quickly and easily!</p>
        <p class="lead p-3">
          <a href="{% url 'groups:group_list' %}" class="btn btn-lg btn-secondary fw-bold">Get a list of groups</a>
        </p>
      {% endblock %}
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
  </footer>
</div>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>