src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import group.urls
import students.urls
import teachers.urls
from core.views import (IndexView, Custom404View, UserLoginView,
                        UserLogoutView, UserRegistrationView, send_test_email,
                        ActivateUserView, UserProfileView)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("__debug__/", include("debug_toolbar.urls")),
    path('jet/', include('jet.urls', 'jet')),
    path("admin/", admin.site.urls),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate_user"),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("students/", include(students.urls)),
    path("teachers/", include(teachers.urls)),
    path("groups/", include(group.urls)),
    path("oauth/", include("social_django.urls", namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()

handler404 = Custom404View.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/group/urls.py
from django.urls import path
from group.views import GroupListView, GroupCreate, GroupUpdateView, GroupDeleteView, GroupDetailView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("create/", GroupCreate.as_view(), name="group_create"),
    path("update/<int:pk>/", GroupUpdateView.as_view(), name="update_group"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("details/<int:pk>/", GroupDetailView.as_view(), name="details_group"),
]

src/students/urls.py
from django.urls import path
from .views import StudentListView, StudentCreate, StudentUpdateView, StudentDeleteView

app_name = "students"

urlpatterns = [
    path("", StudentListView.as_view(), name="get_students"),
    path("create/", StudentCreate.as_view(), name="create_student"),
    path("update/<int:pk>/", StudentUpdateView.as_view(), name="update_student"),
    path("delete/<int:pk>/", StudentDeleteView.as_view(), name="delete_student"),
]

src/students/models.py
import datetime

from django.db import models
from faker import Faker
from django.core.validators import FileExtensionValidator

from core.models import Person
from core.utils.validators import validate_resume
from group.models import Group


class Student(Person):

    grade = models.PositiveSmallIntegerField(null=True, blank=True)
    group = models.ForeignKey(to="group.Group", on_delete=models.CASCADE)
    resume = models.FileField(upload_to="resumes/", null=True, blank=True,
                              validators=[FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']),
                                          validate_resume])

    class Meta:
        verbose_name = "Student list"
        verbose_name_plural = "All students"
        ordering = ("first_name",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                avatar="img/user.png",
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(minimum_age=18, maximum_age=60),
                group=Group.objects.get(id=1)
            )

    def age(self):
        return datetime.datetime.now().year - self.birth_date.year

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.email} ({self.pk})"

src/students/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["avatar", "first_name", "last_name", "email", "group", "resume"]

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex is not a valid email address!!!")
        return email

    def clean_last_name(self):
        return self.normalize_text(self.cleaned_data["last_name"])

    def clean_first_name(self):
        return self.normalize_text(self.cleaned_data["first_name"])

    def clean(self):
        cleaned_data = super().clean()

        first_name = cleaned_data["first_name"]
        last_name = cleaned_data["last_name"]

        if first_name == last_name:
            raise ValidationError("First name and last name cannot be equal!")

        return cleaned_data

src/students/views.py
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from students.forms import StudentForm
from students.models import Student


class StudentListView(ListView):
    model = Student
    template_name = "students/students_list.html"
    context_object_name = "students"

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        search_fields = ["first_name", "last_name", "email"]

        if search_query:
            or_filter = Q()
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search_query})
            queryset = queryset.filter(or_filter)

        return queryset


class StudentCreate(LoginRequiredMixin, CreateView):
    template_name = "students/student_create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "students/student_update.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    queryset = Student.objects.all()


class StudentDeleteView(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = "students/student_delete.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        student = form.instance
        student.delete()
        return HttpResponseRedirect(self.success_url)

src/templates/students/student_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create</button>
        </form>
    </div>
{% endblock content %}

src/templates/students/student_delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Delete">Delete</button>
        </form>
    </div>
{% endblock content %}

src/templates/students/student_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update</button>
        </form>
    </div>
{% endblock content %}

src/templates/students/students_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <div class="d-flex justify-content-between">
        <p>
            <a class="btn btn-primary m-3" role="button" aria-disabled="true" href="{% url 'students:create_student' %}">Add new student</a>
        </p>
        <form class="d-flex" role="search" method="GET" style="width: 50%; height: 2.6em; margin-top: 15px;">
            <input class="form-control me-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button style="width: 15em" class="btn btn-outline-primary" type="submit">Search student</button>
        </form>
    </div>
    <div>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Birth date</th>
                <th scope="col">Age</th>
                <th scope="col">Grade</th>
                <th scope="col">Group number</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for student in students %}
                <tr>
                    <td>
                    {% if student.avatar %}
                        <img src="{{ student.avatar.url }}" alt="avatar {{ student.first_name }}" height="50" width="50">
                    {% else %}
                        <img src="{% static 'img/user.png' %}" alt="avatar" height="50" width="50">
                    {% endif %}
                    </td>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.email }}</td>
                    {% if student.birth_date %}
                        <td>{{ student.birth_date }}</td>
                        <td>{{ student.age }}</td>
                    {% else %}
                        <td>Not available</td>
                        <td>Invalid birth date</td>
                    {% endif %}
                    <td>{{ student.grade }}</td>
                    <td>{{ student.group }}</td>
                    <td>
                        <a type="button" class="btn btn-warning"
                        href="{% url 'students:update_student' student.pk %}">Edit</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-danger"
                        href="{% url 'students:delete_student' student.pk %}">Delete</a>
                    </td>
                    <td>
                        {% if student.resume %}
                        <a type="button" class="btn btn-danger"
                           href="{{ student.resume.url }}" target="_blank">Resume</a>
                        {% else %}
                        <a type="button" class="btn btn-danger"
                        href="{% static 'resumes/cv.pdf' %}">Resume</a>
                    </td>
                        {% endif %}
                </tr>
            {% empty %}
                <p class="fs-1">No students found.</p>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}