src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import group.urls
import students.urls
import teachers.urls
from core.views import (IndexView, Custom404View, UserLoginView,
                        UserLogoutView, UserRegistrationView, send_test_email,
                        ActivateUserView, UserProfileView)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("__debug__/", include("debug_toolbar.urls")),
    path('jet/', include('jet.urls', 'jet')),
    path("admin/", admin.site.urls),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate_user"),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("students/", include(students.urls)),
    path("teachers/", include(teachers.urls)),
    path("groups/", include(group.urls)),
    path("oauth/", include("social_django.urls", namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()

handler404 = Custom404View.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/group/urls.py
from django.urls import path
from group.views import GroupListView, GroupCreate, GroupUpdateView, GroupDeleteView, GroupDetailView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("create/", GroupCreate.as_view(), name="group_create"),
    path("update/<int:pk>/", GroupUpdateView.as_view(), name="update_group"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("details/<int:pk>/", GroupDetailView.as_view(), name="details_group"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreate, TeacherUpdateView, TeacherDeleteView

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="teachers_list"),
    path("create/", TeacherCreate.as_view(), name="teacher_create"),
    path("update/<int:pk>/", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", TeacherDeleteView.as_view(), name="delete_teacher"),
]

src/teachers/models.py
from random import choice

from django.db import models
from faker import Faker

from core.models import Person

from group.models import Group


class Teacher(Person):
    phone_number = models.CharField(max_length=20)
    qualification = models.CharField(max_length=100)
    group = models.ManyToManyField(to="group.Group")

    class Meta:
        verbose_name = "Teacher list"
        verbose_name_plural = "All teachers"
        ordering = ("first_name",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        groups = Group.objects.all()
        for _ in range(count):
            teacher = cls.objects.create(
                avatar="img/user.png",
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                birth_date=faker.date_of_birth(),
                phone_number=faker.phone_number(),
                qualification=faker.job(),
            )
            teacher.group.set([choice(groups)])

src/teachers/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ["avatar", "first_name", "last_name", "email", "birth_date", "phone_number", "qualification", "group"]

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email = self.cleaned_data["email"]

        if "@yandex" in email.lower():
            raise ValidationError("Yandex is not a valid email address!")
        return email

    def clean_subject(self):
        return self.normalize_text(self.cleaned_data["first_name", "last_name", "qualification"])

src/teachers/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .forms import TeacherForm
from .models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = "teachers/teachers_list.html"
    context_object_name = "teachers"


class TeacherCreate(LoginRequiredMixin, CreateView):
    template_name = "teachers/teachers_create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:teachers_list")


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "teachers/teachers_update.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:teachers_list")
    queryset = Teacher.objects.all()


class TeacherDeleteView(LoginRequiredMixin, UpdateView):
    model = Teacher
    template_name = "teachers/teachers_delete.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:teachers_list")
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        teacher = form.instance
        teacher.delete()
        return HttpResponseRedirect(self.success_url)

src/templates/teachers/teachers_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create</button>
        </form>
    </div>
{% endblock content %}

src/templates/teachers/teachers_delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Delete">Delete</button>
        </form>
    </div>
{% endblock content %}

src/templates/teachers/teachers_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}
    <div>
        <p>
            <a class="btn btn-primary m-3" role="button" aria-disabled="true" href="{% url 'teachers:teacher_create' %}">Add new teacher</a>
        </p>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">Photo</th>
                <th scope="col">First name</th>
                <th scope="col">Last name</th>
                <th scope="col">Email</th>
                <th scope="col">Birth date</th>
                <th scope="col">Phone number</th>
                <th scope="col">Qualification</th>
                <th scope="col">Groups</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher in teachers %}
                <tr>
                    <td>
                    {% if teacher.avatar_url %}
                        <img src="{{ teacher.avatar_url }}" alt="Avatar {{ student.first_name }}" height="50" width="50">
                    {% else %}
                        <img src="{% static 'img/user.png' %}" alt="Avatar" height="50" width="50">
                    {% endif %}
                    </td>
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>
                    <td>{{ teacher.email }}</td>
                    {% if teacher.birth_date %}
                        <td>{{ teacher.birth_date }}</td>
                    {% else %}
                        <td>Not available</td>
                        <td>Invalid birth date</td>
                    {% endif %}
                    <td>{{ teacher.phone_number }}</td>
                    <td>{{ teacher.qualification }}</td>
                    <td>
                   {% for group in teacher.group.all %}
                       <a href="{% url 'groups:details_group' group.pk %}">{{ group.group_number }}</a>
                   {% endfor %}
                    </td>
                    <td>
                        <a type="button" class="btn btn-warning"
                        href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-danger"
                        href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

src/templates/teachers/teachers_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update</button>
        </form>
    </div>
{% endblock content %}