src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

import group.urls
import students.urls
import teachers.urls
from core.views import (IndexView, Custom404View, UserLoginView,
                        UserLogoutView, UserRegistrationView, send_test_email,
                        ActivateUserView, UserProfileView)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("__debug__/", include("debug_toolbar.urls")),
    path('jet/', include('jet.urls', 'jet')),
    path("admin/", admin.site.urls),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUserView.as_view(), name="activate_user"),
    path('profile/<int:pk>/', UserProfileView.as_view(), name='user_profile'),
    path("send_test_email/", send_test_email, name="send_test_email"),
    path("students/", include(students.urls)),
    path("teachers/", include(teachers.urls)),
    path("groups/", include(group.urls)),
    path("oauth/", include("social_django.urls", namespace="social")),
]

urlpatterns += staticfiles_urlpatterns()

handler404 = Custom404View.as_view()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/group/urls.py
from django.urls import path
from group.views import GroupListView, GroupCreate, GroupUpdateView, GroupDeleteView, GroupDetailView

app_name = "groups"

urlpatterns = [
    path("", GroupListView.as_view(), name="group_list"),
    path("create/", GroupCreate.as_view(), name="group_create"),
    path("update/<int:pk>/", GroupUpdateView.as_view(), name="update_group"),
    path("delete/<int:pk>/", GroupDeleteView.as_view(), name="delete_group"),
    path("details/<int:pk>/", GroupDetailView.as_view(), name="details_group"),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import TeacherListView, TeacherCreate, TeacherUpdateView, TeacherDeleteView

app_name = "teachers"

urlpatterns = [
    path("", TeacherListView.as_view(), name="teachers_list"),
    path("create/", TeacherCreate.as_view(), name="teacher_create"),
    path("update/<int:pk>/", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete/<int:pk>/", TeacherDeleteView.as_view(), name="delete_teacher"),
]

src/group/models.py
from django.core.validators import MaxValueValidator, MinValueValidator, EmailValidator
from django.db import models
from faker import Faker


class Group(models.Model):
    group_number = models.PositiveSmallIntegerField(default=1, null=True, blank=True, validators=[MinValueValidator(1)])
    email_group = models.EmailField(max_length=120, null=True, blank=True, validators=[EmailValidator()])
    subject = models.CharField(max_length=100, default="No subject")
    students_count = models.PositiveSmallIntegerField(
        default=0, null=True, blank=True, validators=[MinValueValidator(1), MaxValueValidator(50)]
    )
    start_date = models.DateField(null=True, blank=True)
    description = models.TextField(default="No description", null=True, blank=True)

    class Meta:
        verbose_name = "Group list"
        verbose_name_plural = "All groups"
        ordering = ("group_number",)

    @classmethod
    def generate_instances(cls, count):
        faker = Faker()
        for _ in range(count):
            cls.objects.create(
                group_number=faker.random_int(min=1, max=1000),
                email_group=faker.email(),
                subject=faker.job(),
                students_count=faker.random_int(min=1, max=30),
                start_date=faker.date_between(start_date="-30d", end_date="+30d"),
                description=faker.sentence(nb_words=10, variable_nb_words=False),
            )

    def __str__(self):
        return f"{self.group_number} - {self.subject}"

src/group/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from group.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = ["group_number", "email_group", "subject", "students_count", "start_date", "description"]

    @staticmethod
    def normalize_text(text: str) -> str:
        return text.strip().capitalize()

    def clean_email(self):
        email_group = self.cleaned_data["email_group"]

        if "@yandex" in email_group.lower():
            raise ValidationError("Yandex is not a valid email address!")
        return email_group

    def clean_subject(self):
        return self.normalize_text(self.cleaned_data["subject"])

src/group/views.py
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .forms import GroupForm
from .models import Group


class GroupListView(ListView):
    model = Group
    template_name = "groups/group_list.html"
    context_object_name = "groups"


class GroupCreate(LoginRequiredMixin, CreateView):
    template_name = "groups/group_create.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:group_list")


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "groups/group_update.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:group_list")
    queryset = Group.objects.all()


class GroupDeleteView(LoginRequiredMixin, UpdateView):
    model = Group
    template_name = "groups/group_delete.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:group_list")
    pk_url_kwarg = 'pk'

    def form_valid(self, form):
        group = form.instance
        group.delete()
        return HttpResponseRedirect(self.success_url)


class GroupDetailView(DetailView):
    model = Group
    template_name = 'groups/group_details.html'
    context_object_name = 'group'
    form_class = GroupForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = self.form_class(instance=self.object)
        context["form"] = form
        return context

src/templates/groups/group_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 30em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create</button>
        </form>
    </div>
{% endblock content %}

src/templates/groups/group_delete.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Delete">Delete</button>
        </form>
    </div>
{% endblock content %}

src/templates/groups/group_details.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="GET" style="width: 25em;  margin: auto">
            <fieldset disabled>
                {% csrf_token %}
                {{ form|crispy }}
            </fieldset>
            <a class="btn btn-primary" href="{% url 'teachers:teachers_list' %}">Back</a>
        </form>
    </div>
{% endblock content %}

src/templates/groups/group_list.html
{% extends "index.html" %}
{% block content %}
    <div>
        <p>
            <a class="btn btn-primary m-3" role="button" aria-disabled="true" href="{% url 'groups:group_create' %}">Add new group</a>
        </p>
        <table class="table table-dark table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Group Number</th>
                <th scope="col">Email Group</th>
                <th scope="col">Subject</th>
                <th scope="col">Students Count</th>
                <th scope="col">Start Date</th>
                <th scope="col">Description</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
            </thead>
            <tbody>
            {% for group in groups %}
                <tr>
                    <th scope="row">{{ group.id }}</th>
                    <td>{{ group.group_number }}</td>
                    <td>{{ group.email_group }}</td>
                    <td>{{ group.subject }}</td>
                    <td>{{ group.students_count }}</td>
                    <td>{{ group.start_date }}</td>
                    <td>{{ group.description }}</td>
                    <td>
                        <a type="button" class="btn btn-warning"
                        href="{% url 'groups:update_group' group.pk %}">Edit</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-danger"
                        href="{% url 'groups:delete_group' group.pk %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock content %}

src/templates/groups/group_update.html
{% extends "index.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="p-5">
        <form method="POST" style="width: 25em;  margin: auto">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update</button>
        </form>
    </div>
{% endblock content %}